src/AppBundle/Entity/InformationInterface.php
<?php
/**
 * This file is part of the G-Equip Application.
 *
 * PHP version 7.1
 *
 * (c) Alexandre Tranchant <alexandre.tranchant@gmail.com>
 *
 * @category  Repository
 *
 * @author    Alexandre Tranchant <alexandre.tranchant@gmail.com>
 * @copyright 2017 Alexandre Tranchant
 * @license   GNU General Public License, version 3
 *
 * @link      http://opensource.org/licenses/GPL-3.0
 */

namespace AppBundle\Entity;

/**
 * Interface InformationInterface
 *
 * @category Entity
 *
 * @package AppBundle\Entity
 */
interface InformationInterface
{
    /**
     * Return date time creation.
     *
     * @return \DateTime | null
     */
    public function getCreated();
    /**
     * Return date time of the last update.
     *
     * @return \DateTime | null
     */
    public function getUpdated();

    /**
     * Return creator of this entity/
     *
     * @return User | null
     */
    public function getCreator();

    /**
     * Return updater of this entity.
     * @return mixed
     */
    public function getUpdater();

    /**
     * Fluent setter of creator.
     *
     * @param User $creator
     * @return InformationInterface
     */
    public function setCreator(User $creator);

    /**
     * Fluent setter of last updater.
     *
     * @param User $updater
     * @return InformationInterface
     */
    public function setUpdater(User $updater);
}

src/AppBundle/Controller/SettingsController.php
<?php
/**
 * This file is part of the GEquip Application.
 *
 * PHP version 7.1
 *
 * (c) Alexandre Tranchant <alexandre.tranchant@gmail.com>
 *
 * @category Controller
 *
 * @author    Alexandre Tranchant <alexandre.tranchant@gmail.com>
 * @copyright 2017 Alexandre Tranchant
 * @license   GNU General Public License, version 3
 *
 * @link http://opensource.org/licenses/GPL-3.0
 */

namespace AppBundle\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Response;

/**
 * Setting Controller Class.
 *
 * @category Controller
 *
 * @author  Alexandre Tranchant <alexandre.tranchant@gmail.com>
 * @license GNU General Public License, version 3
 *
 * @link http://opensource.org/licenses/GPL-3.0
 */
class SettingsController extends Controller
{
    /**
     * Settings Index.
     *
     * @Route("/settings", name="settings")
     * @Route("/settings/", name="settings_slash")
     *
     * @return Response
     */
    public function indexAction()
    {
        return $this->render('@App/settings/index.html.twig');
    }
}

src/AppBundle/Resources/views/settings/base.html.twig
{% extends '@App/base.html.twig' %}

{% block title %}{{ 'settings.index.title' | trans }} · {{ parent() }}{% endblock %}

{% block content_content %}
    {% block content_breadcrumb %}
        {% if path is defined and path is not null %}
            <ol class="breadcrumb" id="content-breadcrumb">
                {%  for node in path %}
                    <li><a href="{{ path( settings_entity_show, {'slug': node.slug}) }}" title="{{ node.name }}">{{ node.name }}</a></li>
                {% endfor %}
            </ol>
        {% endif %}
    {% endblock content_breadcrumb %}

    {% block content_settings %}{% endblock content_settings %}

    {% block content_logs %}
        {% if logs is defined and logs | length > 0 %}
            <div class="panel panel-default" id="settings-logs">
                <div class="panel-heading">
                    <h3 class="panel-title">{{ 'settings.log' | trans }}</h3>
                </div>
                <table class="table">
                    <thead>
                    <tr>
                        <th class="text-center" id="logs-version">{{ 'settings.log.version' | trans }}</th>
                        <th class="text-center" id="logs-action">{{ 'settings.log.action' | trans }}</th>
                        <th class="text-center" id="logs-date">{{ 'settings.log.date' | trans }}</th>
                        <th class="text-center" id="logs-user">{{ 'settings.log.user' | trans }}</th>
                        <th class="text-center" id="logs-value">{{ 'settings.log.new-value' | trans }}</th>
                    </tr>
                    </thead>
                    {% for log in logs %}
                        <tr>
                            <td headers="logs-version" class="text-center">{{ log.version }}</td>
                            <td headers="logs-action" class="text-center">
                                <span class="label label-default">{{ log.action | trans }}</span>
                            </td>
                            <td headers="logs-date" class="text-center">{{ log.logged | localizeddate('medium','medium')}}</td>
                            <td headers="logs-user" class="text-center">{{ log.username }}</td>
                            <td headers="logs-value">
                                <dl class="dl-horizontal">
                                    {% for row in log.data %}
                                        <dt>{{ row.label | trans }}</dt>
                                        {% if row.none %}
                                            <dd>{{ 'settings.none' | trans }}</dd>
                                        {% elseif row.noMore %}
                                            <dd>{{ 'settings.no-more %entity% %id%' | trans({'id': row.id, 'entity':row.entity}) }}</dd>
                                        {% elseif row.translate %}
                                            <dd>{{ row.name | trans }}</dd>
                                        {% else %}
                                            <dd>{{ row.name }}</dd>
                                        {% endif %}
                                    {% endfor %}
                                </dl>
                            </td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        {% endif %}

    {% endblock content_logs %}
{% endblock content_content %}

{% block content_sidebar %}
    {% block content_action %}{% endblock content_action %}
    <hr>
    {% block content_information %}
        {% if information is defined %}
            <div class="panel panel-default" id="settings-creator-information">
                <div class="panel-heading">
                    <h3 class="panel-title">{{ 'settings.information' | trans }}</h3>
                </div>
                <div class="panel-body">
                    <dl class="dl-horizontal">
                        {% if information.creator %}
                            <dt>{{ 'settings.created.by' | trans}}</dt>
                            <dd>{{ information.creator }}</dd>
                        {% endif %}
                        {% if information.created %}
                            <dt>{{ 'settings.created.at' | trans}}</dt>
                            <dd>{{ information.created | localizeddate('short', 'short') }}</dd>
                        {% endif %}
                        {% if information.updater %}
                            <dt>{{ 'settings.updated.by' | trans}}</dt>
                            <dd>{{ information.updater }}</dd>
                        {% endif %}
                        {% if information.updated %}
                            <dt>{{ 'settings.updated.at' | trans}}</dt>
                            <dd>{{ information.updated | localizeddate('short', 'short') }}</dd>
                        {% endif %}
                    </dl>
                </div>
            </div>
        {% endif %}
    {% endblock content_information %}
{% endblock content_sidebar %}

src/AppBundle/Resources/views/settings/index.html.twig
{% extends '@App/settings/base.html.twig' %}

{% block title %}{{ 'settings.index.title' | trans }}{% endblock title %}

{% block headline %}{{ 'settings.index.title' | trans }}{% endblock headline %}

{% block content_row %}
<div class="panel panel-default">
    <div class="panel-heading"><h2 class="panel-title">{{ 'settings.panel.technic' | trans }}</div>
    <div class="panel-body">
        <div class="row">
            <div class="col-sm-4 text-center">
                <div>
                <span class="fa-stack fa-5x">
                    <i class="fa fa-square-o fa-stack-2x"></i>
                    <i class="fa fa-list fa-stack-1x"></i>
                </span>
                </div>
                <a class="lead" href="{{ path('settings_family_index') }}" title="{{ 'settings.families.link'| trans }}">
                    {{ 'settings.families'| trans }}
                </a>
            </div>
            <div class="col-sm-4 text-center">
                <div>
                <span class="fa-stack fa-5x">
                    <i class="fa fa-square-o fa-stack-2x"></i>
                    <i class="fa fa-cube fa-stack-1x"></i>
                </span>
                </div>
                <a class="lead" href="{{ path('settings_status_index') }}" title="{{ 'settings.status.link'| trans }}">
                    {{ 'settings.status'| trans }}
                </a>
            </div>
        </div>
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading"><h2 class="panel-title">{{ 'settings.panel.human' | trans }}</div>
    <div class="panel-body">
        <div class="row">
            <div class="col-sm-4 text-center">
                <div>
                    <span class="fa-stack fa-5x">
                        <i class="fa fa-square-o fa-stack-2x"></i>
                        <i class="fa fa-building-o fa-stack-1x"></i>
                    </span>
                </div>
                <a class="lead" href="{{ path('settings_service_index') }}" title="{{ 'settings.services.link'| trans }}">
                    {{ 'settings.services'| trans }}
                </a>
            </div>
        </div>
    </div>
</div>
{% endblock content_row %}